apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: configuration-demo
  annotations:
    # Set the annotations defining the maintainer, source, license, and description of your Configuration
    meta.crossplane.io/maintainer: karlderkaefer
    meta.crossplane.io/source: github.com/karlderkaefer/crossplane-composition-template
    # Set the license of your Configuration
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: |
      This Configuration demonstrates how to use the Patch and Transform function to transform a simple string into a ConfigMap.
    meta.crossplane.io/readme: |
      # Configuration Demo
      This is where you can describe your configuration in more detail.
spec:
  # (Optional) Set the minimum version of Crossplane that this Configuration is compatible with
  crossplane:
    version: ">=v1.14.1-0"
  # Add your dependencies here
  dependsOn:
    - provider: xpkg.upbound.io/crossplane-contrib/provider-kubernetes
      version: ">=v0.14.1"
    - function: xpkg.upbound.io/crossplane-contrib/function-patch-and-transform
      version: ">=v0.3.0"
