apiVersion: cfg.example.org/v1alpha1
kind: CCfgResource
metadata:
  namespace: default
  name: simple-example
spec:
  data: "I'm cool!"
  compositionRevisionSelector:
    matchLabels:
      crossplane.io/xrd-version-major: v0